In [1]:
import numpy as np
from numpy.linalg import svd

# 创建用户-项目评分矩阵（示例）
R = np.array([
    [5, 3, 0, 1],
    [4, 0, 0, 1],
    [1, 1, 0, 5],
    [1, 0, 0, 4],
    [0, 1, 5, 4]
])

# 进行奇异值分解
U, sigma, Vt = svd(R, full_matrices=False)

# 将奇异值转换为对角矩阵 
sigma = np.diag(sigma)

# 保留前 k 个奇异值
k = 2
U_k = U[:, :k]
sigma_k = sigma[:k, :k]
Vt_k = Vt[:k, :]

# 计算低秩近似矩阵
R_k = np.dot(U_k, np.dot(sigma_k, Vt_k))

# 打印结果
print("原始用户-项目矩阵:")
print(R)
print("\n低秩近似矩阵:")
print(R_k)

# 预测评分（可以用来推荐）
# 例如，预测用户 1 对项目 2 的评分
user_index = 1
item_index = 2
predicted_rating = R_k[user_index, item_index]
print(f"\n预测用户 {user_index + 1} 对项目 {item_index + 1} 的评分: {predicted_rating}")


原始用户-项目矩阵:
[[5 3 0 1]
 [4 0 0 1]
 [1 1 0 5]
 [1 0 0 4]
 [0 1 5 4]]

低秩近似矩阵:
[[ 5.13406479  1.90612125 -0.72165061  1.5611261 ]
 [ 3.43308995  1.28075331 -0.45629689  1.08967559]
 [ 1.54866643  1.0449763   1.78873709  3.96755551]
 [ 1.17598269  0.80359806  1.40136891  3.08786154]
 [-0.44866693  0.5443561   3.09799526  5.15263893]]

预测用户 2 对项目 3 的评分: -0.45629689375997506


In [2]:
R = np.array([
    [3, 5],
    [4, 0],
])

# 进行奇异值分解
U, sigma, Vt = svd(R, full_matrices=False)

In [5]:
U

array([[-0.89442719, -0.4472136 ],
       [-0.4472136 ,  0.89442719]])

In [6]:
sigma

array([6.32455532, 3.16227766])

In [7]:
Vt

array([[-0.70710678, -0.70710678],
       [ 0.70710678, -0.70710678]])