In [3]:
# NumPy（Numerical Python）是一个开源的 Python 科学计算库。它提供多维数组对象、派生对象（如掩码数组和矩阵）以及用于快速操作数组的各种例程，
# 包括数学、逻辑、形状操作、排序、选择、I/O、离散傅立叶变换、基本线性代数、基本统计运算、随机模拟等等。
import numpy as np

# 假设有一个用户-项目评分矩阵
ratings = np.array([
    [5, 3, 0, 1, 0],
    [4, 0, 0, 1, 0],
    [1, 1, 0, 5, 0],
    [1, 0, 5, 4, 0],
    [0, 1, 5, 4, 0]
])

# 计算每个项目的模长
norm = np.linalg.norm(ratings, axis=1)

# 计算项目之间的点积
dot_product = np.dot(ratings, ratings.T)

# 计算余弦相似度
cosine_similarity = dot_product / (norm[:, np.newaxis] * norm)

# 找到用户喜欢过的所有项目的索引
user_likes = np.where(ratings[0] > 0)[0]

# 根据项目相似度推荐
def recommend(user_index):
    # 获取用户喜欢的项目的相似度
    liked_items_similarity = cosine_similarity[user_index]
    # 排除用户已经喜欢过的项目
    liked_items_similarity[user_likes] = 0
    # 计算推荐得分
    recommended_scores = liked_items_similarity.max(axis=0)
    # 获取推荐项目的索引
    recommended_items = np.argsort(-recommended_scores)
    return recommended_items

# 获取用户 0 的推荐
print("Recommendations for user 0:", recommend(0))

Recommendations for user 0: [0]


In [4]:
import numpy as np

# 假设有用户u和v的喜好列表
likes_u = np.array([1, 1, 0, 0, 1])  # 用户u喜欢第1和第5项
likes_v = np.array([0, 1, 1, 1, 0])  # 用户v喜欢第2, 3和4项

# Jaccard 相似度
jaccard_sim = (np.sum(likes_u & likes_v)) / (np.sum(likes_u | likes_v))

# 余弦相似度
cosine_sim = (np.sum(likes_u & likes_v)) / (np.sqrt(np.sum(likes_u)) * np.sqrt(np.sum(likes_v)))

print("Jaccard Similarity:", jaccard_sim)
print("Cosine Similarity:", cosine_sim)

Jaccard Similarity: 0.2
Cosine Similarity: 0.33333333333333337


In [5]:
import numpy as np

# 创建一个向量
v = np.array([3, 4])

# 计算模长
magnitude = np.linalg.norm(v)
print("The magnitude of the vector is:", magnitude)

The magnitude of the vector is: 5.0


In [6]:
from scipy.sparse import csr_matrix
from scipy.sparse import lil_matrix

# 创建一个稀疏矩阵
rows = [0, 1, 2, 2, 3]
cols = [0, 1, 3, 4, 4]
data = [1, 1, 1, 1, 1]
sparse_matrix = csr_matrix((data, (rows, cols)), shape=(4, 5))

# 打印稀疏矩阵
print("Sparse Matrix (CSR format):")
print(sparse_matrix)

# 转换为密集矩阵
dense_matrix = sparse_matrix.toarray()
print("Dense Matrix:")
print(dense_matrix)

# 稀疏矩阵加法
sparse_add = sparse_matrix + sparse_matrix
print("Sparse Matrix Addition:")
print(sparse_add.toarray())

# 稀疏矩阵乘法
dense_multiply = sparse_matrix.dot(np.array([1, 2, 3, 4, 5]))
print("Sparse Matrix Dot Product with Dense Vector:")
print(dense_multiply)

Sparse Matrix (CSR format):
  (0, 0)	1
  (1, 1)	1
  (2, 3)	1
  (2, 4)	1
  (3, 4)	1
Dense Matrix:
[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 0 1 1]
 [0 0 0 0 1]]
Sparse Matrix Addition:
[[2 0 0 0 0]
 [0 2 0 0 0]
 [0 0 0 2 2]
 [0 0 0 0 2]]
Sparse Matrix Dot Product with Dense Vector:
[1 2 9 5]
